### ISSUE TITLE
Can pytorch-accelerated be used with pytorch-lightning callbacks and loggers?

### ISSUE THREAD

**Issue by GeorgePearse** [Chris-hughes10/pytorch-accelerated#43]
I'm interested in this package for its support of methods like EMA that don't seem to have made it into Lightning yet, but don't want to lost my current experiment tracking setup etc.

**Comment by Chris-hughes10** [comment]
Hi @GeorgePearse, PyTorch-accelerated is designed to be much simpler than lightning so it uses a different callback system. 

Unfortunately, this means that lightning callbacks are not compatible. However, this does mean that it is very easy to migrate most callbacks, often requiring much fewer lines of code. Creating new callbacks is described in the docs [here](https://pytorch-accelerated.readthedocs.io/en/latest/callbacks.html#creating-new-callbacks)

Which callbacks are you interested in using? If it may be useful to others, we could look at making it part of the core library.

**Comment by GeorgePearse** [comment]
2 specific motivations, some methods you have that pytorch-lightning doesn't (yet), and the yoloV7 implementation you released. On the yolov7 note, presumably it should be possible to use the original ONNX export because the model definitions are the same?

This is what I currently use in pytorch-lightning, and from a check of your pytorch-accelerated docs I'd just be missing the aim_logger (Aim is my experiment tracker), and the gcp_model_checkpoint (just saves every checkpoint to cloud storage) 

```
    trainer = Trainer(
        max_epochs=config.trainer.max_epochs,
        accelerator="gpu",
        devices=config.trainer.devices,
        logger=[
            csv_logger,
            aim_logger,
        ],
        callbacks=[
            gcs_model_checkpoint,
            early_stop_callback,
        ],
        log_every_n_steps=5,
        precision=config.trainer.precision,
    )
```

**Comment by Chris-hughes10** [comment]
Cool. In Pytorch-accelerated, loggers are just callbacks, and it should be quite easy to implement those.

For your `aim_callback` I would suggest subclassing [`LogMetricsCallback`](https://pytorch-accelerated.readthedocs.io/en/latest/callbacks.html#pytorch_accelerated.callbacks.LogMetricsCallback), as demonstrated [here](https://pytorch-accelerated.readthedocs.io/en/latest/callbacks.html#example-create-a-custom-logging-callback)

For the `gcs_model_checkpoint`, it should be quite simple to subclass the [`SaveBestModel`](https://pytorch-accelerated.readthedocs.io/en/latest/callbacks.html#pytorch_accelerated.callbacks.SaveBestModelCallback) callback; overriding it so that it saves directly to GCP. Alternatively, you could create a new callback that looks for an existing saved checkpoint on disk and uploads it to GCP.

I'm going to close this issue as the question has been answered, but feel free to post here if you run into any problems and need help implementing those callbacks.
